/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Modelo_dinastia(props) {
  const { nodes, materials } = useGLTF("/static/guerrero_chino.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChnArcher_001.geometry}
        material={nodes.ChnArcher_001.material}
      />
    </group>
  );
}

useGLTF.preload("/static/guerrero_chino.glb");
