/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Barbucha Studio (https://sketchfab.com/lukinec)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chinese-cat-that-is-actually-japanese-45ecc88d44194525aae4a1bb112f6d77
title: Chinese Cat ( that is actually Japanese )
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ModelGato(props) {
  const { nodes, materials } = useGLTF("/static/chinese_cat.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/static/chinese_cat.glb");
